### PR TITLE
Status update adapter

### PR DESCRIPTION
**Pull request by ale-rt**
This Pull request uses adapters to create messages and spread them.

it removes the functions:
 - create_message
 - fake_adapter

A default adapter is register for the INotifiable, interfaced that is attached to all the dexterity items and to StatusUpdate.

It addresses ticket #325 in assembla

### CODE REVIEW

**Comment by ale-rt** [comment]
@do3cc, can you review the PR now?

**Comment by do3cc** [comment]
I am taking care of it right now

**Comment by maartenkling** [comment]
makes sense to me, so ill merge

**Comment by do3cc** [comment]
...

**Comment by maartenkling** [comment]
sorry didnt see your message,

**Pull request merged**
